import { PROJECT_VERSION, type ArtboardPresetId, type ProjectState } from './types'

export const ARTBOARD_PRESETS: Record<ArtboardPresetId, { width: number; height: number; label: string }> = {
  portrait: { width: 1200, height: 1600, label: 'Portrait 3:4' },
  'a-series': { width: 1191, height: 1684, label: 'A Series' },
  square: { width: 1400, height: 1400, label: 'Square' },
  wide: { width: 1920, height: 1080, label: 'Wide 16:9' },
}

export const INK = '#141412'
export const PAPER = '#f4f2ed'

export function createDefaultProject(seed = 1913): ProjectState {
  return {
    version: PROJECT_VERSION,
    seed,
    layoutSeed: 0,
    artboard: { preset: 'portrait', ...ARTBOARD_PRESETS.portrait, background: PAPER },
    lissajous: {
      frequencyX: 3,
      frequencyY: 2,
      phase: Math.PI / 2,
      amplitudeX: 0.92,
      amplitudeY: 0.92,
      rotation: 0,
      offsetX: 0,
      offsetY: 0,
      sampleDensity: 2048,
      presetId: '3:2',
    },
    grid: {
      mode: 'strict',
      marginRestraint: 0.5,
      columnBias: 6,
      rowBias: 8,
      gutterScale: 1,
      baselineRhythm: 1,
      selectedNodeIds: [],
      snapStrength: 0.8,
    },
    typeBlocks: [
      {
        id: 'headline',
        role: 'headline',
        text: 'LISSAJOUS 3:2',
        fontFamily: 'flex',
        size: 120,
        weight: 640,
        width: 118,
        opticalSize: 144,
        lineHeight: 0.98,
        tracking: -0.015,
        textCase: 'upper',
        align: 'left',
        anchor: { col: 0, row: 5, colSpan: 6 },
        materialInfluence: 1,
      },
      {
        id: 'caption',
        role: 'caption',
        text: 'The grid on this poster is built from the self-intersections of a 3:2 curve. Adjust it in the System panel.',
        fontFamily: 'flex',
        size: 24,
        weight: 460,
        width: 100,
        opticalSize: 14,
        lineHeight: 1.4,
        tracking: 0,
        textCase: 'none',
        align: 'left',
        anchor: { col: 4, row: 1, colSpan: 2 },
        materialInfluence: 0.6,
      },
      {
        id: 'metadata',
        role: 'metadata',
        text: 'LBS 001 — RATIO 3:2 — PHASE 90°',
        fontFamily: 'mono',
        size: 16,
        weight: 400,
        width: 100,
        opticalSize: 14,
        lineHeight: 1.2,
        tracking: 0.08,
        textCase: 'upper',
        align: 'left',
        anchor: { col: 0, row: 0, colSpan: 3 },
        materialInfluence: 0.4,
      },
    ],
    glyphField: {
      enabled: false,
      sourceText: 'LISSAJOUS',
      charset: '',
      mode: 'dense',
      density: 0.55,
      contrast: 0.55,
      scale: 20,
      sizeLevels: 2,
      tracking: 0.1,
      lineRhythm: 1,
      orientation: 'grid',
      overprint: false,
      pressureResponse: 0.8,
      randomness: 0,
      seedOffset: 0,
    },
    material: {
      enabled: false,
      preset: 'grain-01',
      pressure: 0.7,
      density: 0.5,
      grainSize: 0.35,
      drift: 0.2,
      fold: 0.3,
      ring: 0.4,
      contrast: 0.65,
      voidStrength: 0.5,
      motion: 0,
      ink: INK,
      paper: PAPER,
    },
    motionLab: {
      easingSource: 'spring',
      stiffness: 14,
      damping: 1.15,
      initialVelocity: 0,
      durationMs: 1100,
      presetId: 'ease',
      pathShape: 'circle',
      pathText: 'LISSAJOUS — ',
      pathTextSize: 46,
      pathSpeed: 0.25,
      pathEased: false,
    },
    export: { scale: 2 },
  }
}
